### ISSUE TITLE
Contributor onboarding call: Mai-Ling Garcia

### ISSUE THREAD

**Issue by lukefretwell** [proudlyserving/book#135]
- [x] Introductions
- [x] Proudly Serving overview (https://proudlyservingbook.com/)
- [x] Editorial process checklist (https://github.com/proudlyserving/proudlyserving.github.io/issues/new/choose)
- [x] Timeline expectations
- [x] Chapter topic and title (https://proudlyservingbook.com/contents/)
- [x] Team agreement (https://proudlyservingbook.com/team-agreement/)

**Comment by rebeccawoodbury** [comment]
Topic: build a diverse team

**Comment by rebeccawoodbury** [comment]
Going to check with her team and let us know next week.
