### ISSUE TITLE
Contributor onboarding call: DC

### ISSUE THREAD

**Issue by lukefretwell** [proudlyserving/book#136]
- [x] Introductions
- [x] Proudly Serving overview (https://proudlyservingbook.com/)
- [ ] Editorial process checklist (https://github.com/proudlyserving/proudlyserving.github.io/issues/new/choose)
- [x] Timeline expectations
- [ ] Chapter topic and title (https://proudlyservingbook.com/contents/)
- [ ] Team agreement (https://proudlyservingbook.com/team-agreement/)

**Comment by rebeccawoodbury** [comment]
Discussed several potential chapter topics, including:
- effective comms
- inclusive management styles
- interoperability/payments
- liberatory design

Will check back in next week.
