### ISSUE TITLE
Chapter final review: Default to open

### ISSUE THREAD

**Issue by lukefretwell** [proudlyserving/book#150]
M = Maintainers
C = Contributors

[Manuscript](https://docs.google.com/document/d/1rruJsEF8-E3qTVCv0Giw2mK43HcNS4d7233rgGk9wjw/edit?usp=sharing)

- [x] Send FYI email to contributor (M - @rebeccawoodbury)
- [x] Edit chapter/author bio (M - @echaschneider)
- [x] Style review (M - @echaschneider)
- [x] Give contributor access to manuscript (M - @rebeccawoodbury)
- [x] Maintainer final chapter review (M - @rebeccawoodbury @lukefretwell)
- [x] Send review your chapter email to contributor (M - @rebeccawoodbury)
- [x] Add acknowledgements (C)
- [x] Contributor final approval (C)
- [x] Updates to website (chapter title, description, bio, etc.) (@lukefretwell)
- [x] Remove access after final edits are accepted (@echa)
- [x] Send chapter final review done email to contributor (M - @rebeccawoodbury)

**Comment by rebeccawoodbury** [comment]
@lukefretwell after we give the contributor access, we need a step to send them an email asking them to review

**Comment by lukefretwell** [comment]
@rebeccawoodbury I updated this issue using the current checklist in the current final review issue template.

Let me know if this needs refined. Will update the other open ones now.

https://github.com/proudlyserving/proudlyserving.github.io/issues/150
