### ISSUE TITLE
Review content icons

### ISSUE THREAD

**Issue by lukefretwell** [proudlyserving/book#211]
**Describe the issue**
We should do a final review of the content icons.

- Contents: https://proudlyservingbook.com/contents/
- Icon library: https://fontawesome.com/search?o=r&m=free

**Comment by MorganGriffin-BloomWorks** [comment]
Created a doc with some thoughts on a few alternatives: https://docs.google.com/document/d/1N77wHmRl9PU7AOhFH2hYqo_poYrwTXbW0Oik0QH_D0Y/edit?usp=sharing

See what you think!
