### ISSUE TITLE
Manuscript review: Swear yourself in

### ISSUE THREAD

**Issue by lukefretwell** [proudlyserving/book#221]
[Reference](https://docs.google.com/document/d/1rruJsEF8-E3qTVCv0Giw2mK43HcNS4d7233rgGk9wjw/edit?usp=sharing)

- [ ] First pass (@lukefretwell / @rebeccawoodbury)
- [ ] Editorial review (@MorganGriffin-BloomWorks)
- [ ] Address/resolve review feedback (@lukefretwell / @rebeccawoodbury)
- [ ] Send author email for resolution (if needed) (@rebeccawoodbury)
- [ ] Reconcile 'Learn more' section (@rebeccawoodbury)
- [ ] Update web page copy

**Comment by MorganGriffin-BloomWorks** [comment]
Add comments in the doc
