### ISSUE TITLE
Add projects documentation

### ISSUE THREAD

**Issue by lukefretwell** [proudlyserving/book#94]
## General

- [x] Add projects section to handbook
- [x] Make /book repo a template repo
- [ ] Set up Calendly
- [ ] Review .gitignore
- [ ] Review README
- [x] Create new PS Slack?
- [ ] Create PS Canva account?
- [ ] Add 'Add chapter categories' to checklist
- [ ] Add new issue templates (ops)
- [ ] Set up project onboarding process (checklist + guide + call agenda)
- [ ] Password sharing (move to 1Password?)

## New project checklist

- [ ] Determine color/subtitle
- [ ] Create new repo
- [ ] Edit README / asset files (other?)
- [ ] Website (subdomain - xyz.proudlyservingbook.com)
- [ ] Set up new GitBook
- [ ] Add Calendly invite for new project
- [ ] Add maintainers to email account
- [ ] New email templates
- [ ] Set up new project board
- [ ] Clean workflow
- [ ] Set up brand assets (https://github.com/proudlyserving/book/tree/main/assets)
- [ ] Set up GitHub team
- [ ] Content (clean categories)
- [ ] Project onboarding call

**Comment by lukefretwell** [comment]
@rebeccawoodbury looks like we would need to upgrade Calendly (for more than one meeting type) and LastPass (to share passwords with more than one person).

We would need to share passwords for:

* Email
* Calendly
* Zoom
* Social - unless MM just handled all for now

**Comment by rebeccawoodbury** [comment]
@lukefretwell for Calendly, I think we can add a question to the event type for the person to select a project. Need to test that idea, but it might work.

And in terms of passwords, I just use the Google account login option for Calendly and Zoom, so they don't have unique logins/passwords. So by sharing the Google account password, I think we're good?
